apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
      - name: docker-image
        image: kumaram/dockerapp:4
        ports:
        - name: docker-port
          containerPort: 5000