apiVersion: v1
kind: Pod
metadata:
  name: dockerapp
  labels:
    app: docker-app
spec:
  containers:
  - name: docker-image
    image: kumaram/dockerapp:3
    ports:
    - name: docker-port
      containerPort: 5000
