apiVersion: v1
kind: Service
metadata:
  name: redisapp-service
spec:
  ports:
  - port: 30011
    targetPort: redis-port
    nodePort: 30011
    protocol: TCP
  selector:
    app: redis-app
  type: NodePort