apiVersion: v1
kind: Pod
metadata:
  name: redisapp
  labels:
    app: redis-app
spec:
  containers:
  - name: redis-image
    image: redis:3.2.0
    ports:
    - name: redis-port
      containerPort: 6379